export const productsDataNew = [
  {
    //_id: "1",
    name: "Miere de tei",
    slug: "1",
    image: "https://i.postimg.cc/BtW39pf0/tei-1.png",
    description:
      "Mierea de tei este o miere cu proprietăți anti-microbiene și anti-inflamatorii, fiind utilizată în tratarea crampelor și a bolilor renale. ",
    additional: "Este fabricata in romania",
    price: 40,
    stoc: 2,
    rating: 4.5,
    numReviews: 20,
  },
  {
    //_id: "2",
    name: "Miere poliflora",
    slug: "2",
    image: "https://i.postimg.cc/qRjpNJkq/poliflora.png",
    description:
      "Mierea poliflora este produsul multor plante de pe camp si are in compozitia sa diverse minerale, vitamine si principii active pe care planta le transmite, prin albine, mierii si, prin miere, omului.  ",
    additional: "Este fabricata in romania",
    price: 35,
    stoc: 0,
    rating: 5,
    numReviews: 22,
  },
  {
    //_id: "3",
    name: "Pachet miere poliflora",
    slug: "3",
    image: "https://i.postimg.cc/W1kWz52J/pachetpoliflora.png",
    description: "acest produs este ",
    additional: "Este fabricata in romania",
    price: 150,
    stoc: 4,
    rating: 4,
    numReviews: 29,
  },
  {
    //_id: "4",
    name: "Miere salcam 4 borcane",
    slug: "4",
    image: "https://i.postimg.cc/3rj34ZxV/pachetsalcam.png",
    description: "acest produs este ",
    additional: "Este fabricata in romania",
    price: 135,
    stoc: 9,
    rating: 4.5,
    numReviews: 20,
  },
  {
    //_id:"5",
    name: "Miere cu fagure",
    slug: "5",
    image: "https://i.postimg.cc/nLKDwD1W/mierecufagure.png",
    description: "acest produs este ",
    additional: "Este fabricata in romania",
    price: 40,
    stoc: 0,
    rating: 4.5,
    numReviews: 20,
  },

  {
    //_id:"5",
    name: "Miere noua",
    slug: "6",
    image: "https://i.postimg.cc/nLKDwD1W/mierecufagure.png",
    description: "acest produs este ",
    additional: "Este fabricata in romania",
    price: 40,
    stoc: 0,
    rating: 4.5,
    numReviews: 20,
  },
  {
    //_id:"5",
    name: "Miere",
    slug: "7",
    image: "https://i.postimg.cc/nLKDwD1W/mierecufagure.png",
    description: "acest produs este ",
    additional: "Este fabricata in romania",
    price: 40,
    stoc: 10,
    rating: 4.5,
    numReviews: 20,
  },
];
